# Playbook que instala las ultimas versiones de software disponibles
# y posteriormente reinicia el nodo gestionado
# $ ansible-playbook -i inventory 03_playbook.yaml -K
---
- name: 'Actualizacion de sistema operativo e instalación de httpd'
  hosts: all
  remote_user: azureuser
  become: true
  tasks:
    - name: 'Ejecucion de tareas comunes'
      include_role:
        name: common
      tags: common

    - name: 'Instalar webserver'
      include_role:
        name: webserver
      when: inventory_hostname in groups['webservers']
      tags: webservers

    - name: 'Instalar databases'
      include_role:
        name: databases
      when: inventory_hostname in groups['databases']
      tags: databases
